import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { IsometricBackdrop } from "@/components/IsometricBackdrop";
import { SiteHeader } from "@/components/SiteHeader";
import { trpc } from "@/lib/trpc";
import { Bot, Copy, ExternalLink, Link2 } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function Agents() {
  const { isAuthenticated } = useAuth();
  const agents = trpc.agents.mine.useQuery(undefined, { enabled: isAuthenticated });
  const copyUrl = async (slug: string) => { await navigator.clipboard.writeText(`${window.location.origin}/agents/${slug}`); toast.success("Shareable URL copied"); };
  if (!isAuthenticated) return <IsometricBackdrop><SiteHeader /><main className="mx-auto max-w-3xl px-4 py-24 text-center sm:px-6"><div className="glass-panel rounded-3xl p-10"><Bot className="mx-auto h-10 w-10 text-teal-600" /><h1 className="display-font mt-5 text-4xl font-bold">Reusable agents live in your workspace.</h1><p className="mt-3 text-slate-600">Sign in to deploy owned prompts as controlled shareable agent URLs.</p><button type="button" onClick={() => startLogin()} className="verbix-button mt-6">Sign in to continue</button></div></main></IsometricBackdrop>;
  return <IsometricBackdrop><SiteHeader /><main className="mx-auto max-w-7xl px-4 pb-20 pt-10 sm:px-6 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-700">Reusable prompt endpoints</p><h1 className="display-font mt-3 text-4xl font-extrabold tracking-tight">Your deployed agents</h1><p className="mt-3 max-w-2xl text-slate-600">Each public agent compiles its source prompt server-side, accepts declared variables, and is protected by an hourly usage limit.</p><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{agents.data?.map(agent => <article key={agent.id} className="glass-panel rounded-3xl p-6"><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-950 text-cyan-200"><Bot className="h-5 w-5" /></span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${agent.isPublic ? "bg-teal-100 text-teal-800" : "bg-slate-100 text-slate-600"}`}>{agent.isPublic ? "Public" : "Private"}</span></div><h2 className="display-font mt-5 text-2xl font-bold">{agent.name}</h2><p className="mt-2 break-all text-xs text-slate-500">/agents/{agent.slug}</p><div className="mt-6 flex gap-2"><Link href={`/agents/${agent.slug}`} className="inline-flex items-center gap-1.5 rounded-full bg-slate-950 px-3.5 py-2 text-xs font-bold text-white"><ExternalLink className="h-3.5 w-3.5" /> Open</Link><button type="button" onClick={() => copyUrl(agent.slug)} className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3.5 py-2 text-xs font-bold text-slate-700"><Copy className="h-3.5 w-3.5" /> Copy URL</button></div></article>)}{!agents.isLoading && agents.data?.length === 0 && <div className="glass-panel col-span-full rounded-3xl p-10 text-center"><Link2 className="mx-auto h-8 w-8 text-blue-600" /><h2 className="display-font mt-4 text-2xl font-bold">No agents deployed yet.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">Open one of your saved prompts, then use Deploy as agent to create a controlled reusable URL.</p><Link href="/workspace" className="verbix-button mt-5">Open workspace</Link></div>}</div></main></IsometricBackdrop>;
}
