import { Filter, Search, SlidersHorizontal, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { IsometricBackdrop } from "@/components/IsometricBackdrop";
import { PromptCard } from "@/components/PromptCard";
import { SiteHeader } from "@/components/SiteHeader";
import { trpc } from "@/lib/trpc";

export default function Discover() {
  const [location] = useLocation();
  const initialQuery = useMemo(() => new URLSearchParams(location.split("?")[1] || "").get("query") || "", [location]);
  const [query, setQuery] = useState(initialQuery);
  const [category, setCategory] = useState("");
  const [tag, setTag] = useState("");
  const [model, setModel] = useState("");
  const [sort, setSort] = useState<"recent" | "trending" | "featured">("recent");
  const categories = trpc.discovery.categories.useQuery();
  const tags = trpc.discovery.tags.useQuery();
  const prompts = trpc.discovery.list.useQuery({ query: query || undefined, category: category || undefined, tag: tag || undefined, model: model || undefined, sort, limit: 60 });

  return <IsometricBackdrop><SiteHeader /><main className="mx-auto max-w-7xl px-4 pb-20 pt-12 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-700">Public prompt library</p><h1 className="display-font mt-3 text-5xl font-extrabold tracking-tight">Find your next <span className="text-blue-600">starting point.</span></h1><p className="mt-4 text-lg leading-7 text-slate-600">Search the approved library by use case, category, model fit, and structured tags.</p></div>
    <div className="glass-panel mt-9 rounded-3xl p-4"><div className="grid gap-3 lg:grid-cols-[minmax(220px,1fr)_auto_auto_auto_auto]"><label className="flex min-w-0 items-center gap-3 rounded-2xl bg-white px-4 py-3"><Search className="h-5 w-5 text-slate-400" /><span className="sr-only">Search prompts</span><input value={query} onChange={event => setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm font-medium outline-none placeholder:text-slate-400" placeholder="Search by task, intent, or workflow" /></label><label className="flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm font-bold text-slate-700"><Filter className="h-4 w-4 text-teal-600" /><span className="sr-only">Category</span><select value={category} onChange={event => setCategory(event.target.value)} className="max-w-32 bg-transparent outline-none"><option value="">All categories</option>{categories.data?.map(item => <option key={item.id} value={item.slug}>{item.name}</option>)}</select></label><label className="flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm font-bold text-slate-700"><span className="text-teal-600">#</span><span className="sr-only">Tag</span><select value={tag} onChange={event => setTag(event.target.value)} className="max-w-28 bg-transparent outline-none"><option value="">All tags</option>{tags.data?.map(item => <option key={item.id} value={item.slug}>{item.name}</option>)}</select></label><label className="flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm font-bold text-slate-700"><span className="text-blue-600">AI</span><span className="sr-only">Model compatibility</span><select value={model} onChange={event => setModel(event.target.value)} className="max-w-28 bg-transparent outline-none"><option value="">All models</option><option value="OpenAI">OpenAI</option><option value="Anthropic">Anthropic</option><option value="Google">Google</option><option value="General">General</option></select></label><label className="flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm font-bold text-slate-700"><SlidersHorizontal className="h-4 w-4 text-blue-600" /><span className="sr-only">Sort prompts</span><select value={sort} onChange={event => setSort(event.target.value as typeof sort)} className="bg-transparent outline-none"><option value="recent">Recent</option><option value="trending">Trending</option><option value="featured">Featured</option></select></label></div></div>
    <div className="mt-8 flex items-center justify-between"><p className="text-sm text-slate-600">{prompts.isLoading ? "Finding prompts..." : `${prompts.data?.length ?? 0} prompt${(prompts.data?.length ?? 0) === 1 ? "" : "s"} found`}</p><Link href="/compose" className="inline-flex items-center gap-2 rounded-full bg-slate-950 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-slate-800"><Sparkles className="h-4 w-4 text-cyan-200" /> Create one</Link></div>
    {prompts.error ? <div className="mt-7 rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-900">The library could not be loaded. {prompts.error.message}</div> : <div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{prompts.data?.map(prompt => <PromptCard key={prompt.id} prompt={prompt} />)}{!prompts.isLoading && prompts.data?.length === 0 && <div className="glass-panel col-span-full rounded-3xl p-10 text-center"><Search className="mx-auto h-8 w-8 text-slate-400" /><h2 className="display-font mt-4 text-2xl font-bold">No prompts match this view.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">Try a broader search, clear a filter, or add a structured prompt to the library.</p><button type="button" onClick={() => { setQuery(""); setCategory(""); setTag(""); setModel(""); }} className="mt-5 rounded-full border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700">Clear filters</button></div>}</div>}
  </main></IsometricBackdrop>;
}
